# Generated by Django 5.1.4 on 2026-09-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='serving', max_length=50)),
                ('serving_size_grams', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fats_g', models.FloatField()),
                ('fiber_g', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0.85)),
                ('source', models.CharField(default='llm_estimate', max_length=50)),
                ('llm_generated', models.BooleanField(default=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='meals.meal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', '-created_at'], name='meals_meal_user_id_ab2104_idx'),
        ),
    ]
