# Generated by Django 5.1.4 on 2026-09-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='input_method',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text'), ('image', 'Image')], default='voice', max_length=10),
        ),
    ]
