# Generated by Django 5.1.4 on 2026-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_input_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_category',
            field=models.CharField(choices=[('early_morning', 'Early Morning'), ('breakfast', 'Breakfast'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime')], default='lunch', max_length=20),
        ),
    ]
